accelerator: gpu
batch_size: 128
check_val_every_n_epoch: 10
ckpt_every_n_epoch: 100
cnn_padding: 1
datamodule: cifar10
devices: 1
lr: 0.1
lr_scheduler: cosine
max_epochs: 100
model: cnn
val_split: 0.1
